config/routes.rb
Billnemo::Application.routes.draw do
  resources :expenses

  resources :bills

  root :to => 'dashboard#index'
  devise_for :users

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :bill_date, :name, :total_items, :total_users, :type_id, :user_id, :expenses_attributes
  has_many :expenses
  accepts_nested_attributes_for :expenses
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :amount, :bill_id, :deleted, :name, :split, :split_type, :userexpenses_attributes
  belongs_to :bill
  has_many :userexpenses
  accepts_nested_attributes_for :userexpenses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
end

app/models/userexpense.rb
class Userexpense < ActiveRecord::Base
  attr_accessible :split, :split_type, :user_id, :expense_id
  belongs_to :user
  belongs_to :userexpense
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	# flash[:notice] = 'green'
  	# flash[:alert] = 'red'
  	# flash[:message] = 'yellow'
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(params[:expense])

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper  
  def bootstrap_flash
   flash_messages = []
   flash.each do |type, message|
     # Skip Devise :timeout and :timedout flags
     next if type == :timeout
     next if type == :timedout
     type = :success if type == :notice
     type = :error   if type == :alert
     text = content_tag(:div, 
              content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
              message, :class => "alert fade in alert-#{type}")
     flash_messages << text if message
   end
   flash_messages.join("\n").html_safe
 end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/bills/_form.html.erb
<%= form_for @bill, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bill_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bill_date, :class => 'date_select', 'data-behaviour' => 'datepicker' %>
    </div>
  </div>

  <%= nested_form_for @bill do |nf| %>
    <%= nf.fields_for :expenses do |expense_form| %>
      <div class="control-group">
        <%= expense_form.label :name, :class => 'control-label' %>
        <div class="controls">
          <%= expense_form.text_field :name, :class => 'text_field'  %>
        </div>
      </div>
      <div class="control-group">
        <%= expense_form.label :amount, :class => 'control-label' %>
        <div class="controls">
          <%= expense_form.number_field :amount, :class => 'text_field'  %>
        </div>
      </div>
      <%= expense_form.link_to_remove "Remove this Expense" %>
    <% end %>
    <p><%= nf.link_to_add "Add an Expense", :expenses %></p>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bills_path, :class => 'btn' %>
  </div>
  <% end %>
<% end %>

app/views/bills/edit.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/index.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:bill_date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= link_to bill.id, bill_path(bill) %></td>
        <td><%= bill.name %></td>
        <td><%= bill.bill_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bill_path(bill), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bill_path(bill),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bill_path,
            :class => 'btn btn-primary' %>

app/views/bills/new.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/show.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bill.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_date) %>:</strong></dt>
  <dd><%= @bill.bill_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bills_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bill_path(@bill), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bill_path(@bill),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/dashboard/_not_signed_in.html.erb
<% content_for :title, "Bill Sharing - Without all the Fluff" %>
<div class="row">
  <div class="span8">
    <div class="hero-unit">
      <h1>Welcome - now, why are you here?</h1>
      <p>
         Finally! A simple, usable and to the point Bill Sharing and Management Tool. Got Roomies? Spotted a friend? Paid for dinner? Do you want to keep track of all that? Well, if you answer yes to the last question, your search just (hopefully) ended. After facing stupid issues with a whole bunch of bill sharing applications, We decided to make our own. And then we thought, why not open it up to people? Why not let everyone in on the fun. So we open sourced the whole project! You can find it on <a href="https://github.com/arun057/billnemo" alt="https://github.com/arun057/billnemo">Github</a>.
        </p>
      <p>Do you develop? Have an awesome idea for the application? Wanna contribute some design changes? Or just want to write documentation for other people? Head on over to Github.</p>
      <p>
        <%= link_to "Ready? Sign Up", new_user_registration_path, :class => 'btn btn-primary btn-large' %>
      </p>
    </div>
  </div>

  <div class="span4">
    <div class="login well">
      <%= form_for("user", :url => user_session_path) do |f| %>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">@</span>
          <%= f.text_field :email , :placeholder => 'email' , :class => 'span3' %>
        </div>
      </div>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">*</span>
          <%= f.password_field :password , :placeholder => 'password' , :class => 'span3' %>
        </div>
      </div>
        <label class="checkbox">
        <%= f.check_box :remember_me %>  Remember me
        </label>
          <%= f.submit 'Sign in', :class => 'btn btn-success' %>
        <%= link_to "New here? Sign Up", new_user_registration_path, :class => 'btn btn-primary' %>
        <p>
          <%= link_to "Forgot your password?", new_password_path('user') %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_signed_in.html.erb
<div class="row">
	<div class="span3 moneybox offset3">
		<ul class="green">
			<li class="money_header">People owe you</li>
			<li class="money">
				<sup>$</sup>
				<h1 class="bigmoney">600</h1>
			</li>
		</ul>
	</div>
	<div class="span3 moneybox">
		<ul class="red">
			<li class="money_header">You owe</li>
			<li class="money">
				<sup>$</sup>
				<h1 class="bigmoney">800000</h1>
			</li>
		</ul>
	</div>
</div>

<div class="row divider">
	<div class="span3 square_box">
		<li>Add a bill</li>
	</div>
	<div class="span3 square_box">
		<li></li>
	</div>
	<div class="span3 square_box">
		<li></li>
	</div>
	<div class="span3 square_box">
		<li></li>
	</div>
</div>

app/views/dashboard/index.html.erb
<% if user_signed_in? then %>
  <%= render :partial => 'signed_in' %>
<% else %>
  <%= render :partial => 'not_signed_in' %>
<% end %>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :bill_id %><br />
    <%= f.number_field :bill_id %>
  </div>
  <div class="field">
    <%= f.label :split %><br />
    <%= f.number_field :split %>
  </div>
  <div class="field">
    <%= f.label :split_type %><br />
    <%= f.number_field :split_type %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>Bill</th>
    <th>Split</th>
    <th>Split type</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.name %></td>
    <td><%= expense.amount %></td>
    <td><%= expense.bill_id %></td>
    <td><%= expense.split %></td>
    <td><%= expense.split_type %></td>
    <td><%= expense.deleted %></td>
    <td><%= link_to 'Show', expense %></td>
    <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
    <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @expense.name %>
</p>

<p>
  <b>Amount:</b>
  <%= @expense.amount %>
</p>

<p>
  <b>Bill:</b>
  <%= @expense.bill_id %>
</p>

<p>
  <b>Split:</b>
  <%= @expense.split %>
</p>

<p>
  <b>Split type:</b>
  <%= @expense.split_type %>
</p>

<p>
  <b>Deleted:</b>
  <%= @expense.deleted %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-<%= name %>">
  <a class="close" data-dismiss="alert">x</a>
  <%= msg %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "" %> | Billnemo</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <% # favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <% # favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <% # favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <% # favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'assets/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
       <div class="navbar-inner">
         <div class="container">
           <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </a>
           <a class="brand" href="../">Billnemo</a>
           <div class="nav-collapse" id="main-menu">
            <ul class="nav" id="main-menu-left">
              <li><a href="#">About</a></li>
            </ul>
            <% if user_signed_in? %>
              <ul class="nav pull-right" id="main-menu-right">
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">you <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Account</a></li>
                    <li class="divider"></li>
                    <li><%= link_to "Log out", destroy_user_session_path, :method => :delete  %></li>
                  </ul>
                </li>
              </ul>
              <% end %>
           </div>
         </div>
       </div>
    </div>

    <div class="container">
    	<%= bootstrap_flash %>
	  </div>

    <div class="container">
          <%= yield %>
    </div> <!-- /container -->
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>